server:
  port: 8662
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/kami?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    pool:
      enabled: true
      max-size: 50
      initial-size: 10
      validation-query: select 1
  application:
    name: kakami

logging:
  level:
    com.lanrenspace.kakami: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.apache.ibatis.r2dbc: DEBUG